services:
  app:
    build:
      context: .
      args:
        FULL_NAME: ${FULL_NAME}
    ports:
      - "100.73.60.108:54321:3000"
    environment:
      - FULL_NAME=${FULL_NAME}
    restart: unless-stopped
