name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: FULL_NAME
          script: |
            cd /home/artertendean/Documents/test/silver-octo-barnacle
            git pull origin main
            sed -i "s/__FULL_NAME__/$FULL_NAME/g" Dockerfile
            docker compose build
            git checkout Dockerfile
            docker compose up -d
        env:
          FULL_NAME: ${{ secrets.FULL_NAME }}
